name: craftsman
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0-178.1.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  intl_phone_number_input: ^0.7.0+2
  cached_network_image: ^3.2.0
  transparent_image: ^2.0.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets:
   - assets/
   - assets/images/

